baseURL = "https://anotherbug.com"
title = "鼠标土豆"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true
theme = "PaperMod"

paginate = 15
enableEmoji = true
enableRobotsTXT = true
pygmentsUseClasses = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[frontmatter]
date = [":filename", ":default"]

[permalinks]
posts = "/:year/:month/:day/:slug"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5

  [[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    weight = 6

  [[menu.main]]
    name = "Uses"
    url = "/tools/"
    weight = 7

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 8

  [[menu.main]]
    name = "Academics"
    url = "/main/"
    weight = 9

[params]
  env = "production"
  author = "mousepotato"
  description = "mousepotato 的个人博客"
  keywords = ["blog", "Networking", "Hugo", "GNU/Linux", "Linux", "Ubuntu", "Programming"]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true
  disableSpecial1stPost = true
  mainSections = ["posts"]
  images = ["assets/images/profile.jpg"]

  [params.label]
    text = "鼠标土豆"

  [params.homeInfoParams]
    Title = "鼠标土豆"
    Content = "「人生最好的境界是丰富的安静」 — 周国平"

  [[params.socialIcons]]
    name = "github"
    title = "GitHub"
    url = "https://github.com/mousepotato"

  [[params.socialIcons]]
    name = "rss"
    title = "RSS"
    url = "/index.xml"

  [params.assets]
    favicon = "/assets/images/favicon.ico"
    favicon16x16 = "/assets/images/favicon.ico"
    favicon32x32 = "/assets/images/favicon.ico"
    apple_touch_icon = "/assets/images/favicon.ico"

[services]
  [services.googleAnalytics]
    ID = "UA-11501178-2"
